name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Build the APK using a pre-built Buildozer Docker image
      - name: Build APK
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app \
          kivy/buildozer:latest bash -c "
          cd /app &&
          apt-get update &&
          apt-get install -y lib32stdc++6 lib32z1 &&
          buildozer android debug"

      # Step 3: Upload the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: bin/*.apk
